### ISSUE TITLE
Feature request: Component per tab mode

### ISSUE THREAD

**Issue by ghost** [ractivejs/playground#3]
Would be nice to have a mode in playground that allows you to:

- Write in component file format.
- Write one component per tab.
    - Designate one tab's component to be the main/entrypoint component.
    - Instantiated and auto-mounted to output on save.
- With this tab-only approach, the browser becomes half editor, half output. Minimal UI.
    - Kinda like JSBin with only JS and Output panes open.
- Settings gear opens a modal for settings to not disrupt editor-output layout.

More like plunkr but less file-y. This way, it promotes the use of component files and/or provides an alternate way to write things.

**Comment by evs-chris** [comment]
Something like this has been on my list of things to do for a while. I was thinking something like the svelte repl. It would pull in rollup and the main script would be the entry point. You could add files and import from the main script.

Close follow-up on that would be a button to download the project as a zip with either rollup or webpack ready to go as soon as you unzip and `npm i`.

**Comment by ghost** [comment]
Totally forgot Svelte is doing this already.  Lemme change the title to "Copy Svelte REPL". 😁

**Comment by evs-chris** [comment]
Done!
