### ISSUE TITLE
Bug with script filename editing 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/playground#5]
# Reproduction 

1. Go to [this ground](https://ractive.js.org/playground/?file=i18n.js#N4IgLiBcIgNCBnKN4GNlxACyqATlAHYCuANqfEpANogD0dqAJoQHQBWCTApqQJYA3PK0LcwdQgAcAtnTwBDVGEHcAAtyYBzbnMXKB3DggD8ARhABdAL7xpUU-ABmVaqELzp3ZH0I8AHqwKSiqsWGDSpJioAPaEYNxxyAA8CLzcSgAEAvKkxNwAvAA6IMDAqghY8ngarHymABxspPKEmlZWxRmxALSola0FxeWV1Uy1DU3R8kwAFKqE0Tys2bncAJTFAHyFhBkZSdGSyrFZOXlFJcDEvtyOPhrtWzMAIrfyZGBrSXSHx4Tbu32vz4sU2pgAzOCAOzfYGgnZ7A5HEH-ABi0Tw0hysOR8MBSL+mwAavJNHkcYSdt9UqR0mAAVSsKZNgAJXikaKwfYISQtTalOqNGbuTwZAA+YoyAHIAEp6FRStbtam8-4AQm+TIZhBSqDwfCOAL2fGkkgxYAygt2jjw0Wk0tYdCtRilAG4ERkPTFCAgLQBBSSSDL5DJy4IGVjcPzxXwzYAevbEVKQDLUK0zNYWWAJjLxU3NeIpgAkABUAKIAWQACgAZP3l7OAvaoBAIYsAYQAyp3G3tm62AJJMFNS+SBqUeqxrd2EL2xX0ZMdBkMAdx8TGiK9YS+DGVEK4yAckcZzYCq2jAI4ARosAJ4TwFTmfUvUG+k7Km+2+0o0ZJkZYAMhiDk8BTABiAAGCD6gaeRXQyDodToL8fx2EAbDcDwvGgZ1OCiWIYwgaBaQtDlpg0XdHByVIZx2KMzTwC0eCoj4Mkca5ghOSRck0HwZl+BA1gAj8wGqMBiDwa0OL+ONQ3lAwuR8X0WlQbgEKE+Mm0tH0z0IVTQl4SRuDwBBqH4o4EHFSVgCnEQsKs6UrSlCxdxmX08CE-JNmErTm3nUiWk0Xcw30QwKiqDQAHExBmKVnWaVpFRnPs+29BcsWXOTwzCkYopigADZ0MtYItgAStp8unHNjUcDIZgyjIADJGoydztIyDKhLEiTdgy6h3IsZKUoyXhUh84a+z4Wr6rHJqWpCkJnjLAAhABVSKhLS6JaVYFcqkIGZ8oAOWiXMFB9AsUUXbI+GaK9aTYjFpVK9yrCldrSvKqxKqGibusk1rRN+vtEJSxCcymuq1TIngmA06qMhhiiQ1EvJgcKMAFojcLRk7GK4omVgYalLlyuDbzNImvydI62aQyxnKIqYaKwEOoqxxKsrAu+qrfMm6a1U68aqZquqyfyCXpQhaFFSy0LWBxjQ8dZwrCeKz7ufyrlAIZkcZQAFlQKFTCJbgpSfBGUtGtTIZmcXJaldFMRyWXUjAEsTW4aJiFZjNyblkJFaYZW2bVjmNdab7tYDgwR07Pg8Bjs2py5cEoIg3mRb2a3LWm+2QylEkyTNoS3Y9zxvd9zzvIZhXcuDgr2ckTmvq1gCk71+TuG6PgKnNtYuVMdPM6p0G+wxi2tLHqwZysdCsxAW5vBuAIgnlsIInQoA)
2. Double-click i18n.js
3. See the name turns into `<input />` and lets you edit the name of the script 
4. Double-click `index.ractive.html`
5. See `i18n.js` input is filled with "index.ractive.html" string.

**Comment by evs-chris** [comment]
I'm not seeing that behavior on mobile chrome... what browser?

**Comment by ceremcem** [comment]
Chromium Version 67.0.3396.87 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

![playground-issue5](https://user-images.githubusercontent.com/6639874/43926687-c23f7f60-9c33-11e8-98e6-37b550d14ac1.gif)

**Comment by evs-chris** [comment]
Ohhhh... more than one at a time. Yeah, that shouldn't be too hard to fix. Sorry, I missed a step up there 😅

**Comment by evs-chris** [comment]
Should be good now!

**Comment by ceremcem** [comment]
Yes, now works as expected.
